spring.application.name=inventory-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/inventory_db?serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:inventory_user}
spring.datasource.password=${DB_PASSWORD:inventory_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:Yn2khR54nA3sX7pL9mQw8eR1tY5uIo0pF6vB4jKcDgHfSjNlWxMzCbVqEyUoTi}
jwt.expiration=${JWT_EXPIRATION:86400000}
